const mongoose=require("mongoose");

const authSchema=new mongoose.Schema({
    name:{
        type:String,
        require:[true,"Please provide name"]
    },
    email:{
        type:String,
        require:[true,"please provide email"]
    },
    phone:{
        type:Number,
        require:[true,"please provide phone number"]
    },
    image:{
        type:String,
        default:""
    },
    password:{
        type:String,
        require:[true,"please provide password"]
    },
    decoration:{
        name:{
            type:String,
            default:""
        },
        minBookingPrice:{
            type:Number,
            default:0
        },
        available:{
            type:Number,
            default:0
        },
        image1:{
            type:String,
            default:""
        }, 
        image2:{
            type:String,
            default:""
        },
        address:{
            type:String,
            default:"",
        },
        description:{
            type:String,
            default:""
        }
    },
    djSound:{
        name:{
            type:String,
            default:""
        },
        minBookingPrice:{
            type:Number,
            default:0
        },
        available:{
            type:Number,
            default:0
        },
        image1:{
            type:String,
            default:""
        }, 
        image2:{
            type:String,
            default:""
        },
        address:{
            type:String,
            default:"",
        },
        description:{
            type:String,
            default:""
        }   
    },
    marriegeHall:{
        name:{
            type:String,
            default:""
        },
        minBookingPrice:{
            type:Number,
            default:0
        },
        available:{
            type:Number,
            default:0
        },
        image1:{
            type:String,
            default:""
        }, 
        image2:{
            type:String,
            default:""
        },
        address:{
            type:String,
            default:"",
        },
        description:{
            type:String,
            default:""
        }   
    },
    photographer:{
        name:{
            type:String,
            default:""
        },
        minBookingPrice:{
            type:Number,
            default:0
        },
        available:{
            type:Number,
            default:0
        },
        image1:{
            type:String,
            default:""
        }, 
        image2:{
            type:String,
            default:""
        },
        address:{
            type:String,
            default:"",
        },
        description:{
            type:String,
            default:""
        }   
    },
    car:{
        name:{
            type:String,
            default:""
        },
        minBookingPrice:{
            type:Number,
            default:0
        },
        available:{
            type:Number,
            default:0
        },
        totalCar:{
            type:Number,
            default:0
        },
        image1:{
            type:String,
            default:""
        }, 
        image2:{
            type:String,
            default:""
        },
        address:{
            type:String,
            default:"",
        },
        description:{
            type:String,
            default:""
        } 
    },

},{timestamps:true})

module.exports=mongoose.model('User',authSchema)